### ISSUE TITLE
Run test suite with sanitizers

### ISSUE THREAD

**Issue by PhilMiller** [NOAA-OWP/ngen#536]
We want to see if the code as it exists currently triggers any reports from AddressSanitizer (ASan) or UndefinedBehaviorSanitizer (UBSan).

If it passes, then we can add a CI job to ensure that this stays clean.

**Comment by PhilMiller** [comment]
Here's a preliminary set of test failures that appear when built with `-DCMAKE_C_FLAGS=-fsanitize=address -DCMAKE_CXX_FLAGS=-fsanitize=address`:

```
  Test  #39: GIUH_Test.TestInit0
  Test  #40: GIUH_Test.TestOutput0
  Test  #41: GIUH_Test.TestManualOrdinates0
  Test  #42: GIUH_Test.TestOutput1
  Test  #43: GIUH_Test.TestOutput2
  Test #325: GIUH_Test.TestInit0
  Test #326: GIUH_Test.TestOutput0
  Test #327: GIUH_Test.TestManualOrdinates0
  Test #328: GIUH_Test.TestOutput1
  Test #329: GIUH_Test.TestOutput2
  Test #472: GIUH_Test.TestInit0
  Test #473: GIUH_Test.TestOutput0
  Test #474: GIUH_Test.TestManualOrdinates0
  Test #475: GIUH_Test.TestOutput1
  Test #476: GIUH_Test.TestOutput2
```

**Comment by PhilMiller** [comment]
UBSan does not surface any new test failures

**Comment by PhilMiller** [comment]
```
$ ./test/test_giuh --gtest_filter=GIUH_Test.TestInit0

Running main() from /Users/phil/Code/noaa/ngen/test/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = GIUH_Test.TestInit0
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from GIUH_Test
[ RUN      ] GIUH_Test.TestInit0
=================================================================
==72208==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x000109d001f8 at pc 0x00010249fd50 bp 0x00016dac8b10 sp 0x00016dac8b08
READ of size 8 at 0x000109d001f8 thread T0
    #0 0x10249fd4c in giuh::giuh_kernel_impl::interpolate_regularized_cdf() GIUH.cpp:134
    #1 0x102364074 in giuh::giuh_kernel_impl::giuh_kernel_impl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<double, std::__1::allocator<double> >, std::__1::vector<double, std::__1::allocator<double> >, unsigned int) GIUH.hpp:102
    #2 0x102340028 in giuh::giuh_kernel_impl::giuh_kernel_impl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<double, std::__1::allocator<double> >, std::__1::vector<double, std::__1::allocator<double> >, unsigned int) GIUH.hpp:98
    #3 0x10233c190 in giuh::giuh_kernel_impl::giuh_kernel_impl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<double, std::__1::allocator<double> >, std::__1::vector<double, std::__1::allocator<double> >) GIUH.hpp:124
    #4 0x1024abab0 in giuh::GiuhJsonReader::build_giuh_kernel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, boost::property_tree::basic_ptree<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >) GiuhJsonReader.cpp:16
    #5 0x1024ae4ec in giuh::GiuhJsonReader::get_giuh_kernel_for_id(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) GiuhJsonReader.cpp:78
    #6 0x102338dc4 in GIUH_Test_TestInit0_Test::TestBody() GIUH_Test.cpp:71
    #7 0x10247d810 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2599
    #8 0x1023e0d90 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2635
    #9 0x1023e0960 in testing::Test::Run() gtest.cc:2674
    #10 0x1023e3200 in testing::TestInfo::Run() gtest.cc:2853
    #11 0x1023e6194 in testing::TestSuite::Run() gtest.cc:3012
    #12 0x10240a418 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5870
    #13 0x10248b224 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2599
    #14 0x1024094d8 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2635
    #15 0x102408fe8 in testing::UnitTest::Run() gtest.cc:5444
    #16 0x10249e23c in RUN_ALL_TESTS() gtest.h:2293
    #17 0x10249e198 in main gtest_main.cc:51
    #18 0x1029b1088 in start+0x204 (dyld:arm64e+0x5088)

0x000109d001f8 is located 8 bytes to the left of 22256-byte region [0x000109d00200,0x000109d058f0)
allocated by thread T0 here:
    #0 0x102dddef0 in wrap__Znwm+0x74 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x4def0)
    #1 0x1023490bc in void* std::__1::__libcpp_operator_new<unsigned long>(unsigned long) new:235
    #2 0x102348fe0 in std::__1::__libcpp_allocate(unsigned long, unsigned long) new:261
    #3 0x1023669bc in std::__1::allocator<double>::allocate(unsigned long) allocator.h:108
    #4 0x102366804 in std::__1::allocator_traits<std::__1::allocator<double> >::allocate(std::__1::allocator<double>&, unsigned long) allocator_traits.h:262
    #5 0x102365e48 in std::__1::vector<double, std::__1::allocator<double> >::__vallocate(unsigned long) vector:1015
    #6 0x10236a060 in std::__1::vector<double, std::__1::allocator<double> >::vector(std::__1::vector<double, std::__1::allocator<double> > const&) vector:1280
    #7 0x10233bf98 in std::__1::vector<double, std::__1::allocator<double> >::vector(std::__1::vector<double, std::__1::allocator<double> > const&) vector:1273
    #8 0x1024aba84 in giuh::GiuhJsonReader::build_giuh_kernel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, boost::property_tree::basic_ptree<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >) GiuhJsonReader.cpp:16
    #9 0x1024ae4ec in giuh::GiuhJsonReader::get_giuh_kernel_for_id(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) GiuhJsonReader.cpp:78
    #10 0x102338dc4 in GIUH_Test_TestInit0_Test::TestBody() GIUH_Test.cpp:71
    #11 0x10247d810 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2599
    #12 0x1023e0d90 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2635
    #13 0x1023e0960 in testing::Test::Run() gtest.cc:2674
    #14 0x1023e3200 in testing::TestInfo::Run() gtest.cc:2853
    #15 0x1023e6194 in testing::TestSuite::Run() gtest.cc:3012
    #16 0x10240a418 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5870
    #17 0x10248b224 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2599
    #18 0x1024094d8 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2635
    #19 0x102408fe8 in testing::UnitTest::Run() gtest.cc:5444
    #20 0x10249e23c in RUN_ALL_TESTS() gtest.h:2293
    #21 0x10249e198 in main gtest_main.cc:51
    #22 0x1029b1088 in start+0x204 (dyld:arm64e+0x5088)

SUMMARY: AddressSanitizer: heap-buffer-overflow GIUH.cpp:134 in giuh::giuh_kernel_impl::interpolate_regularized_cdf()
Shadow bytes around the buggy address:
  0x0070213bffe0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0070213bfff0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0070213c0000: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0070213c0010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0070213c0020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0070213c0030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x0070213c0040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0070213c0050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0070213c0060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0070213c0070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0070213c0080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==72208==ABORTING
Abort trap: 6
```


```
$ test/test_bmi_fortran --gtest_filter=Bmi_Fortran_Adapter_Test.Profile

Running main() from /Users/phil/Code/noaa/ngen/test/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = Bmi_Fortran_Adapter_Test.Profile
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Bmi_Fortran_Adapter_Test
[ RUN      ] Bmi_Fortran_Adapter_Test.Profile
=================================================================
==72217==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x00016d425688 at pc 0x000104d3783c bp 0x00016d424ac0 sp 0x00016d424278
READ of size 48 at 0x00016d425688 thread T0
    #0 0x104d37838 in wrap_memcpy+0x13c (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x17838)
    #1 0x10593ee18 in _gfortrani_reshape_packed+0x38 (libgfortran.5.dylib:arm64+0x102e18)
    #2 0x107d4cd54 in __bmitestbmi_MOD_test_set_double bmi_test_bmi_fortran.f90:904
    #3 0x1044475d8 in set_value_double+0x3ac (libiso_c_bmi.1.0.0.dylib:arm64+0x35d8)
    #4 0x102e513e0 in models::bmi::Bmi_Fortran_Adapter::inner_set_value_double(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, double*) Bmi_Fortran_Adapter.hpp:796
    #5 0x102e46948 in models::bmi::Bmi_Fortran_Adapter::inner_set_value(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) Bmi_Fortran_Adapter.hpp:730
    #6 0x102e4668c in models::bmi::Bmi_Fortran_Adapter::SetValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*) Bmi_Fortran_Adapter.cpp:151
    #7 0x102a1ff0c in Bmi_Fortran_Adapter_Test_Profile_Test::TestBody() Bmi_Fortran_Adapter_Test.cpp:1560
    #8 0x102ce0410 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2599
    #9 0x102c48474 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2635
    #10 0x102c48044 in testing::Test::Run() gtest.cc:2674
    #11 0x102c4a8e4 in testing::TestInfo::Run() gtest.cc:2853
    #12 0x102c4d878 in testing::TestSuite::Run() gtest.cc:3012
    #13 0x102c71ad0 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5870
    #14 0x102cee4a4 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2599
    #15 0x102c70b90 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2635
    #16 0x102c706a0 in testing::UnitTest::Run() gtest.cc:5444
    #17 0x102d014bc in RUN_ALL_TESTS() gtest.h:2293
    #18 0x102d01418 in main gtest_main.cc:51
    #19 0x104581088 in start+0x204 (dyld:arm64e+0x5088)

Address 0x00016d425688 is located in stack of thread T0 at offset 456 in frame
    #0 0x102a1f5dc in Bmi_Fortran_Adapter_Test_Profile_Test::TestBody() Bmi_Fortran_Adapter_Test.cpp:1541

  This frame has 38 object(s):
    [32, 56) 'output_names' (line 1545)
    [96, 120) 'input_names' (line 1546)
    [160, 200) 'saved_times' (line 1548)
    [240, 241) 'to_micros' (line 1552)
    [256, 280) 'shape' (line 1556)
    [320, 336) 'agg.tmp'
    [352, 360) 'ref.tmp' (line 1556)
    [384, 408) 'agg.tmp26'
    [448, 456) 'data' (line 1559)
    [480, 504) 'agg.tmp39' <== Memory access at offset 456 partially underflows this variable
    [544, 560) 'agg.tmp49'
    [576, 588) 'ref.tmp50' (line 1561)
    [608, 632) 'agg.tmp62'
    [672, 680) 's1' (line 1567)
    [704, 712) 'e1' (line 1569)
    [736, 760) 'ref.tmp83' (line 1570)
    [800, 808) 'ref.tmp90' (line 1570)
    [832, 840) '__begin2' (line 1573)
    [864, 872) '__end2' (line 1573)
    [896, 920) 'name' (line 1573)
    [960, 968) 's2' (line 1575)
    [992, 1016) 'values' (line 1576)
    [1056, 1064) 'e2' (line 1577)
    [1088, 1112) 'ref.tmp122' (line 1578)
    [1152, 1160) 'ref.tmp128' (line 1578)
    [1184, 1192) '__begin2153' (line 1582)
    [1216, 1224) '__end2157' (line 1582)
    [1248, 1272) 'name165' (line 1582)
    [1312, 1320) 's3' (line 1584)
    [1344, 1368) 'values173' (line 1585)
    [1408, 1416) 'e3' (line 1586)
    [1440, 1464) 'ref.tmp182' (line 1587)
    [1504, 1512) 'ref.tmp188' (line 1587)
    [1536, 1544) '__begin1' (line 1594)
    [1568, 1576) '__end1' (line 1594)
    [1600, 1624) 'key' (line 1596)
    [1664, 1672) 'agg.tmp239'
    [1696, 1704) 'agg.tmp243'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x17838) in wrap_memcpy+0x13c
Shadow bytes around the buggy address:
  0x00702daa4a80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00702daa4a90: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 00 00 f2
  0x00702daa4aa0: f2 f2 f2 f2 00 00 00 f2 f2 f2 f2 f2 00 00 00 00
  0x00702daa4ab0: 00 f2 f2 f2 f2 f2 01 f2 00 00 00 f2 f2 f2 f2 f2
  0x00702daa4ac0: 00 00 f2 f2 f8 f2 f2 f2 00 00 00 f2 f2 f2 f2 f2
=>0x00702daa4ad0: 00[f2]f2 f2 00 00 00 f2 f2 f2 f2 f2 00 00 f2 f2
  0x00702daa4ae0: f8 f8 f2 f2 00 00 00 f2 f2 f2 f2 f2 f8 f2 f2 f2
  0x00702daa4af0: f8 f2 f2 f2 f8 f8 f8 f2 f2 f2 f2 f2 f8 f2 f2 f2
  0x00702daa4b00: f8 f2 f2 f2 f8 f2 f2 f2 f8 f8 f8 f2 f2 f2 f2 f2
  0x00702daa4b10: f8 f2 f2 f2 f8 f8 f8 f2 f2 f2 f2 f2 f8 f2 f2 f2
  0x00702daa4b20: f8 f8 f8 f2 f2 f2 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2
==72217==ABORTING
Abort trap: 6
```

**Comment by PhilMiller** [comment]
Per https://blogs.oracle.com/linux/post/improving-application-security-with-undefinedbehaviorsanitizer-ubsan-and-gcc
* Any given build should only have one or ASan or UBSan enabled
* The build should include `-g -fno-omit-frame-pointer`
* The build should include `-O1` or higher "in order for all errors to be detected"

**Comment by PhilMiller** [comment]
#580 adds Address Sanitizer to all of the CI builds. We can figure out down the line whether/how we want to slot in UBSan as well

**Comment by PhilMiller** [comment]
ASan ran into issues in #766
