### ISSUE TITLE
Fix ASan-reported heap-buffer-overflow in BMI Python adapter tests

### ISSUE THREAD

**Issue by PhilMiller** [NOAA-OWP/ngen#541]
Discovered in the course of #536

> `cmake -S . -B build-asan2 -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=/opt/homebrew/opt/boost\@1.76/ -DBMI_C_LIB_ACTIVE=ON -D BMI_FORTRAN_ACTIVE:BOOL=ON -DCMAKE_CXX_FLAGS=-fsanitize=address -DCMAKE_C_FLAGS=-fsanitize=address`

```
./test/test_bmi_python --gtest_filter=Bmi_Py_Formulation_Test.get_response_0_a
Running main() from /Users/phil/Code/noaa/ngen/test/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = Bmi_Py_Formulation_Test.get_response_0_a
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Bmi_Py_Formulation_Test
[ RUN      ] Bmi_Py_Formulation_Test.get_response_0_a
Definition of "au" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-accepted.xml", line 123, overrides prefixed-unit "1.6605402e-45 kilogram"
Definition of "kt" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 105, overrides prefixed-unit "1000000 kilogram"
Definition of "microns" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 416, overrides prefixed-unit "1e-15 second"
Definition of "ft" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 527, overrides prefixed-unit "1e-12 kilogram"
Definition of "yd" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 536, overrides prefixed-unit "8.64e-20 second"
Definition of "pt" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 790, overrides prefixed-unit "1e-09 kilogram"
Definition of "at" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 1259, overrides prefixed-unit "1e-15 kilogram"
Definition of "ph" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 1889, overrides prefixed-unit "3.6e-09 second"
Definition of "nt" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 1898, overrides prefixed-unit "1e-06 kilogram"
WARN: Unit conversion unsuccessful - Returning unconverted value! ("Unable to parse out_units value -")
WARN: Unit conversion unsuccessful - Returning unconverted value! ("Unable to convert mm s^-1 to kg m^-2")
Invalid value of specific humidity with no supplied rel. humidity in ET calc. function:
Relative Humidity: -99.900000 percent
Specific Humidity: 0.009300 kg/kg
WARN: Unit conversion unsuccessful - Returning unconverted value! ("Unable to parse out_units value -")
=================================================================
==59431==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x000105d74418 at pc 0x000103c6f83c bp 0x00016dd47430 sp 0x00016dd46be8
READ of size 48 at 0x000105d74418 thread T0
    #0 0x103c6f838 in wrap_memcpy+0x13c (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x17838)
    #1 0x109eb14b4 in _contig_to_contig+0x28 (_multiarray_umath.cpython-311-darwin.so:arm64+0x10d4b4)
    #2 0x109e47d88 in raw_array_assign_array+0x2bc (_multiarray_umath.cpython-311-darwin.so:arm64+0xa3d88)
    #3 0x109e4886c in PyArray_AssignArray+0x324 (_multiarray_umath.cpython-311-darwin.so:arm64+0xa486c)
    #4 0x109e54260 in PyArray_NewCopy+0x38 (_multiarray_umath.cpython-311-darwin.so:arm64+0xb0260)
    #5 0x102496010 in pybind11::array::array(pybind11::dtype const&, pybind11::detail::any_container<long>, pybind11::detail::any_container<long>, void const*, pybind11::handle) numpy.h:743
    #6 0x1024951e4 in pybind11::array::array(pybind11::buffer_info const&, pybind11::handle) numpy.h:774
    #7 0x1024b0620 in pybind11::array_t<double, 16>::array_t(pybind11::buffer_info const&, pybind11::handle) numpy.h:1053
    #8 0x1024b00c4 in pybind11::array_t<double, 16>::array_t(pybind11::buffer_info const&, pybind11::handle) numpy.h:1053
    #9 0x102492fac in void models::bmi::Bmi_Py_Adapter::set_value<double>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, double*) Bmi_Py_Adapter.hpp:765
    #10 0x102439470 in models::bmi::Bmi_Py_Adapter::SetValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*) Bmi_Py_Adapter.hpp:535
    #11 0x1024cabe0 in realization::Bmi_Module_Formulation<models::bmi::Bmi_Py_Adapter>::set_model_inputs_prior_to_update(double const&, long) Bmi_Module_Formulation.hpp:1139
    #12 0x1024c8bd4 in realization::Bmi_Py_Formulation::get_response(long, long) Bmi_Py_Formulation.cpp:105
    #13 0x1021dbb60 in Bmi_Py_Formulation_Test_get_response_0_a_Test::TestBody() Bmi_Py_Formulation_Test.cpp:409
    #14 0x102408bc4 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2599
    #15 0x102370294 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2635
    #16 0x10236fe64 in testing::Test::Run() gtest.cc:2674
    #17 0x102372704 in testing::TestInfo::Run() gtest.cc:2853
    #18 0x102375698 in testing::TestSuite::Run() gtest.cc:3012
    #19 0x1023998f0 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5870
    #20 0x102416c58 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2599
    #21 0x1023989b0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2635
    #22 0x1023984c0 in testing::UnitTest::Run() gtest.cc:5444
    #23 0x102429c70 in RUN_ALL_TESTS() gtest.h:2293
    #24 0x102429bcc in main gtest_main.cc:51
    #25 0x10305d088 in start+0x204 (dyld:arm64e+0x5088)

0x000105d74418 is located 0 bytes to the right of 8-byte region [0x000105d74410,0x000105d74418)
allocated by thread T0 here:
    #0 0x103ca6018 in wrap__Znam+0x74 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x4e018)
    #1 0x102585554 in std::__1::shared_ptr<double> realization::Bmi_Module_Formulation<models::bmi::Bmi_Py_Adapter>::as_c_array<double, std::__1::__wrap_iter<double*> >(std::__1::__wrap_iter<double*>, std::__1::__wrap_iter<double*>) Bmi_Module_Formulation.hpp:995
    #2 0x10257f248 in std::__1::shared_ptr<void> realization::Bmi_Module_Formulation<models::bmi::Bmi_Py_Adapter>::get_values_as_type<std::__1::__wrap_iter<double*> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__wrap_iter<double*>, std::__1::__wrap_iter<double*>) Bmi_Module_Formulation.hpp:1022
    #3 0x1024ca464 in realization::Bmi_Module_Formulation<models::bmi::Bmi_Py_Adapter>::set_model_inputs_prior_to_update(double const&, long) Bmi_Module_Formulation.hpp:1131
    #4 0x1024c8bd4 in realization::Bmi_Py_Formulation::get_response(long, long) Bmi_Py_Formulation.cpp:105
    #5 0x1021dbb60 in Bmi_Py_Formulation_Test_get_response_0_a_Test::TestBody() Bmi_Py_Formulation_Test.cpp:409
    #6 0x102408bc4 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2599
    #7 0x102370294 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2635
    #8 0x10236fe64 in testing::Test::Run() gtest.cc:2674
    #9 0x102372704 in testing::TestInfo::Run() gtest.cc:2853
    #10 0x102375698 in testing::TestSuite::Run() gtest.cc:3012
    #11 0x1023998f0 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5870
    #12 0x102416c58 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2599
    #13 0x1023989b0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2635
    #14 0x1023984c0 in testing::UnitTest::Run() gtest.cc:5444
    #15 0x102429c70 in RUN_ALL_TESTS() gtest.h:2293
    #16 0x102429bcc in main gtest_main.cc:51
    #17 0x10305d088 in start+0x204 (dyld:arm64e+0x5088)

SUMMARY: AddressSanitizer: heap-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x17838) in wrap_memcpy+0x13c
Shadow bytes around the buggy address:
  0x007020bce830: fa fa fd fa fa fa fd fa fa fa 00 fa fa fa fd fa
  0x007020bce840: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x007020bce850: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x007020bce860: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x007020bce870: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
=>0x007020bce880: fa fa 00[fa]fa fa fd fa fa fa 00 05 fa fa fd fa
  0x007020bce890: fa fa fd fa fa fa fd fa fa fa fd fa fa fa 04 fa
  0x007020bce8a0: fa fa 04 fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x007020bce8b0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x007020bce8c0: fa fa fd fa fa fa fd fa fa fa fd fd fa fa fd fa
  0x007020bce8d0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==59431==ABORTING
Abort trap: 6
```

**Comment by PhilMiller** [comment]
Looking at the stack trace compared to #549, it seems that this shares the same underlying cause of scalar output feeding array input, and the same change from https://github.com/NOAA-OWP/ngen/pull/534/files#diff-ae1264775c477c87bced0f5ed3e382966fe721ec49ee36e7498e86fd01b9727dR1122 resolves the ASan report.
