### ISSUE TITLE
Fix ASan-reported overflow in Fortran BMI Formulation Test

### ISSUE THREAD

**Issue by PhilMiller** [NOAA-OWP/ngen#549]
Following #538, another ASan report from a different Fortran BMI test:

```
$ test/test_bmi_fortran "--gtest_filter=Bmi_Fortran_Formulation_Test.GetOutputLineForTimestep_0_a" "--gtest_also_run_disabled_tests"
Running main() from /Users/phil/Code/noaa/ngen/test/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = Bmi_Fortran_Formulation_Test.GetOutputLineForTimestep_0_a
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Bmi_Fortran_Formulation_Test
[ RUN      ] Bmi_Fortran_Formulation_Test.GetOutputLineForTimestep_0_a
lib_file[0]: ../extern/test_bmi_fortran/cmake_build/libtestbmifortranmodel.dylib
lib_file[1]: ../extern/test_bmi_fortran/cmake_build/libtestbmifortranmodel.dylib
Definition of "au" in "/Volumes/Cased/Code/noaa/ngen/build-asan-4/UDUNITS-2/build/share/udunits/udunits2-accepted.xml", line 123, overrides prefixed-unit "1.6605402e-45 kilogram"
Definition of "kt" in "/Volumes/Cased/Code/noaa/ngen/build-asan-4/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 105, overrides prefixed-unit "1000000 kilogram"
Definition of "microns" in "/Volumes/Cased/Code/noaa/ngen/build-asan-4/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 416, overrides prefixed-unit "1e-15 second"
Definition of "ft" in "/Volumes/Cased/Code/noaa/ngen/build-asan-4/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 527, overrides prefixed-unit "1e-12 kilogram"
Definition of "yd" in "/Volumes/Cased/Code/noaa/ngen/build-asan-4/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 536, overrides prefixed-unit "8.64e-20 second"
Definition of "pt" in "/Volumes/Cased/Code/noaa/ngen/build-asan-4/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 790, overrides prefixed-unit "1e-09 kilogram"
Definition of "at" in "/Volumes/Cased/Code/noaa/ngen/build-asan-4/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 1259, overrides prefixed-unit "1e-15 kilogram"
Definition of "ph" in "/Volumes/Cased/Code/noaa/ngen/build-asan-4/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 1889, overrides prefixed-unit "3.6e-09 second"
Definition of "nt" in "/Volumes/Cased/Code/noaa/ngen/build-asan-4/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 1898, overrides prefixed-unit "1e-06 kilogram"
WARN: Unit conversion unsuccessful - Returning unconverted value! ("Unable to convert mm s^-1 to m")
WARN: Unit conversion unsuccessful - Returning unconverted value! ("Unable to convert kg kg-1 to m")
WARN: Unit conversion unsuccessful - Returning unconverted value! ("Unable to convert Pa to s")
WARN: Unit conversion unsuccessful - Returning unconverted value! ("Unable to convert mm s^-1 to m")
=================================================================
==32845==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x000106a64eb8 at pc 0x0001049eb83c bp 0x00016dacbb00 sp 0x00016dacb2b8
READ of size 48 at 0x000106a64eb8 thread T0
    #0 0x1049eb838 in wrap_memcpy+0x13c (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x17838)
    #1 0x1041b2e18 in _gfortrani_reshape_packed+0x38 (libgfortran.5.dylib:arm64+0x102e18)
    #2 0x108508d54 in __bmitestbmi_MOD_test_set_double bmi_test_bmi_fortran.f90:904
    #3 0x103d875d8 in set_value_double+0x3ac (libiso_c_bmi.1.0.0.dylib:arm64+0x35d8)
    #4 0x1027ab770 in models::bmi::Bmi_Fortran_Adapter::inner_set_value_double(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, double*) Bmi_Fortran_Adapter.hpp:796
    #5 0x1027a0cd8 in models::bmi::Bmi_Fortran_Adapter::inner_set_value(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void*) Bmi_Fortran_Adapter.hpp:730
    #6 0x1027a0a1c in models::bmi::Bmi_Fortran_Adapter::SetValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*) Bmi_Fortran_Adapter.cpp:151
    #7 0x1027c9394 in realization::Bmi_Module_Formulation<models::bmi::Bmi_Fortran_Adapter>::set_model_inputs_prior_to_update(double const&, long) Bmi_Module_Formulation.hpp:1139
    #8 0x1027c7354 in realization::Bmi_Fortran_Formulation::get_response(long, long) Bmi_Fortran_Formulation.cpp:181
    #9 0x1023fa34c in Bmi_Fortran_Formulation_Test_GetOutputLineForTimestep_0_a_Test::TestBody() Bmi_Fortran_Formulation_Test.cpp:322
    #10 0x10263a758 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2599
    #11 0x1025a27bc in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2635
    #12 0x1025a238c in testing::Test::Run() gtest.cc:2674
    #13 0x1025a4c2c in testing::TestInfo::Run() gtest.cc:2853
    #14 0x1025a7bc0 in testing::TestSuite::Run() gtest.cc:3012
    #15 0x1025cbe18 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5870
    #16 0x1026487ec in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2599
    #17 0x1025caed8 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2635
    #18 0x1025ca9e8 in testing::UnitTest::Run() gtest.cc:5444
    #19 0x10265b804 in RUN_ALL_TESTS() gtest.h:2293
    #20 0x10265b760 in main gtest_main.cc:51
    #21 0x103e39088 in start+0x204 (dyld:arm64e+0x5088)

0x000106a64eb8 is located 0 bytes to the right of 8-byte region [0x000106a64eb0,0x000106a64eb8)
allocated by thread T0 here:
    #0 0x104a22018 in wrap__Znam+0x74 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x4e018)
    #1 0x10247152c in std::__1::shared_ptr<double> realization::Bmi_Module_Formulation<models::bmi::Bmi_Fortran_Adapter>::as_c_array<double, std::__1::__wrap_iter<double*> >(std::__1::__wrap_iter<double*>, std::__1::__wrap_iter<double*>) Bmi_Module_Formulation.hpp:995
    #2 0x102450818 in std::__1::shared_ptr<void> realization::Bmi_Module_Formulation<models::bmi::Bmi_Fortran_Adapter>::get_values_as_type<std::__1::__wrap_iter<double*> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__wrap_iter<double*>, std::__1::__wrap_iter<double*>) Bmi_Module_Formulation.hpp:1022
    #3 0x1027c8c18 in realization::Bmi_Module_Formulation<models::bmi::Bmi_Fortran_Adapter>::set_model_inputs_prior_to_update(double const&, long) Bmi_Module_Formulation.hpp:1131
    #4 0x1027c7354 in realization::Bmi_Fortran_Formulation::get_response(long, long) Bmi_Fortran_Formulation.cpp:181
    #5 0x1023fa34c in Bmi_Fortran_Formulation_Test_GetOutputLineForTimestep_0_a_Test::TestBody() Bmi_Fortran_Formulation_Test.cpp:322
    #6 0x10263a758 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2599
    #7 0x1025a27bc in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2635
    #8 0x1025a238c in testing::Test::Run() gtest.cc:2674
    #9 0x1025a4c2c in testing::TestInfo::Run() gtest.cc:2853
    #10 0x1025a7bc0 in testing::TestSuite::Run() gtest.cc:3012
    #11 0x1025cbe18 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5870
    #12 0x1026487ec in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2599
    #13 0x1025caed8 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2635
    #14 0x1025ca9e8 in testing::UnitTest::Run() gtest.cc:5444
    #15 0x10265b804 in RUN_ALL_TESTS() gtest.h:2293
    #16 0x10265b760 in main gtest_main.cc:51
    #17 0x103e39088 in start+0x204 (dyld:arm64e+0x5088)

SUMMARY: AddressSanitizer: heap-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x17838) in wrap_memcpy+0x13c
Shadow bytes around the buggy address:
  0x007020d6c980: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x007020d6c990: fa fa fd fd fa fa fd fd fa fa fd fd fa fa 00 02
  0x007020d6c9a0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x007020d6c9b0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x007020d6c9c0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
=>0x007020d6c9d0: fa fa fd fd fa fa 00[fa]fa fa fd fa fa fa fd fa
  0x007020d6c9e0: fa fa fd fa fa fa fd fd fa fa fd fd fa fa fd fd
  0x007020d6c9f0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x007020d6ca00: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x007020d6ca10: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x007020d6ca20: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==32845==ABORTING
Abort trap: 6
```

_Originally posted by @PhilMiller in https://github.com/NOAA-OWP/ngen/issues/538#issuecomment-1608381303_

**Comment by PhilMiller** [comment]
The 'fix' for this is essentially https://github.com/NOAA-OWP/ngen/pull/534/files#diff-ae1264775c477c87bced0f5ed3e382966fe721ec49ee36e7498e86fd01b9727dR1122 - broadcasting scalar BMI model outputs to array BMI model inputs

@hellkite500 and I discussed the broader implications around this, and he's going to open an issue to discuss it more broadly.
